### ISSUE TITLE
Adding new vendor

### ISSUE THREAD

**Issue by Ausrinetfix** [tadvaas/tSoft#10]
Make county mandatory when adding a new vendor

**Comment by tadvaas** [comment]
if(empty($county)){
			$opt['e'] = true;
			$opt['m'].= 'Please select trading address county'.PHP_EOL;
		}
		if(empty($bill_county)){
			$opt['e'] = true;
			$opt['m'].= 'Please select office address county'.PHP_EOL;
		}
